name: connect-publish
on:
  release:
    types: [published]
  pull_request:

jobs:
  connect-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: latest
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            local::.

      - name: Create manifest.json
        shell: Rscript {0}
        run: |
          rsconnect::writeManifest()

      - name: Publish Connect content
        if: github.event_name != 'pull_request'
        uses: rstudio/actions/connect-publish@main
        env:
          CONNECT_ENV_SET_AZ_STORAGE_CONTAINER_INPUTS: ${{ secrets.AZ_STORAGE_CONTAINER_INPUTS }}
          CONNECT_ENV_SET_AZ_STORAGE_CONTAINER_RESULTS: ${{ secrets.AZ_STORAGE_CONTAINER_RESULTS }}
          CONNECT_ENV_SET_AZ_STORAGE_CONTAINER_SUPPORT: ${{ secrets.AZ_STORAGE_CONTAINER_SUPPORT }}
          CONNECT_ENV_SET_AZ_STORAGE_EP: ${{ secrets.AZ_STORAGE_EP }}
          CONNECT_ENV_SET_AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
          CONNECT_ENV_SET_GOLEM_CONFIG_ACTIVE: "production"
        with:
          url: ${{ secrets.CONNECT_SERVER }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: logged_in
          namespace: nhp
          dir: |
            .:/mitigator_comparisons
